version: '3.1'

services:
  bot:
    build: ./HelpService
    restart: always
    env_file:
      - ".env.prod"
    command: python main.py

  ui:
    build: ./KharkivBayraktarFE
    volumes:
      - ui-build:/app/build
    env_file:
      - ".env.prod"
    ports:
      - "3000:3000"
    command: "npm run build"

  backend:
    build: ./HelpServiceBE
    restart: always
    env_file:
      - ".env.prod"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ui
      - backend
    volumes:
      - ui-build:/app/build

volumes:
  ui-build: