version: '3.1'

services:
  ui:
    build: ./KharkivBayraktarFE
    volumes:
      - ./data/build:/app/build
    env_file:
      - ".env.dev"
    ports:
      - "3000:3000"
    command: "npm run build"

  backend:
    build: ./HelpServiceBE
    restart: always
    env_file:
      - ".env.dev"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ui
      - backend
    volumes:
      - ./data/build:/app/build