version: '3.1'

services:
  backend:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 80:8000
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
