version: '3.1'

services:
  ui:
    build: ./
    volumes:
      - ./build:/app/build
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    command: "npm run build"
    # command: "npm start"
    
volumes:
  ui-build: